resolver: lts-13.4

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

# The dependency graph which was previously here has been dropped in favor of
# PNG output from the script `scripts/package-dep-graph.sh`, which uses
# `stack dot` to construct a graph which represents the current state exactly.

packages:
- util
- util/test
- networking
- binary
- binary/test
- crypto
- crypto/test
- core
- core/test
- db
- db/test
- infra
- infra/test
- chain
- chain/test
- x509
- tools
- tools/post-mortem
- lib
- node
- rocksdb
- mpt
- contract
 
- location:
    git: https://github.com/sealchain/sealchain-crypto.git
    commit: d3b0a937cb31d11c771e03909bfd8fe993dfd08c
  extra-dep: true

# to be removed when haskell-ip is in the current stackage version
- location:
    git: https://github.com/andrewthad/haskell-ip
    commit: 9bb453139aa82cc973125091800422a523e1eb8f
  extra-dep: true

- location:
    git: https://github.com/yihuang/aeson-options.git
    commit: bb1ee59aa6652198a90cd90fb09b1f2fcb8efd1f
  extra-dep: true

## Vendored/Forked dependencies
#
# For these projects, please include a note describing:
# 1. why we're using a fork
# 2. what branch the commit is on
# 3. a link to the PR that upstreams the patch
#
# Has support for canonical cbor. This commit is pulled into `master`. I've
# posted a GitHub issue requesting a Hackage release:
# https://github.com/well-typed/cborg/issues/171
- location:
    git: https://github.com/well-typed/cborg
    commit: e352b0eae0825165723bd566bca08d060371e956
  subdirs:
  - cborg
  extra-dep: true

# this extra-dep is to avoid printing microseconds with unicode
# no PR upstream was made
# TODO(parsonsmatt): why was this change done?
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true

# not reviewing this too deeply as we're dumping kademlia
- location:
    git: https://github.com/yihuang/kademlia.git
    commit: 0b5495fb3233dbb1f108ea372515369cd64a7baf
  extra-dep: true

# This defines a bundle type and attribute:
# https://github.com/haskell-distributed/network-transport/compare/master...serokell:018a50b9042c2115c3ec9c9fd5ca5f28737dd29c?expand=1
# Seems relatively straightforward to PR.
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true

# This doesn't have much difference at all with the upstream master:
# https://github.com/haskell-distributed/network-transport-tcp/compare/master...serokell:3d56652123bd296dc759cd31947eb2a17924e68a?expand=1
# As above, seems relatively straightforward to PR.
- location:
    git: https://github.com/yihuang/network-transport-tcp.git
    commit: 73b64331f056ef84a8e0b551b7e88738261c1304
  extra-dep: true

# This one has more changes:
# https://github.com/haskell-distributed/network-transport-inmemory/compare/master...avieth:5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a?expand=1
# Do we have an issue that documents why we made these changes, so we can make a PR upstream?
- location:
      git: https://github.com/avieth/network-transport-inmemory
      commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
  extra-dep: true

# Waiting on the space leak bug fix PR to be merged:
# https://github.com/acid-state/acid-state/pull/104
- location:
    git: https://github.com/parsonsmatt/acid-state
    commit: a1b23e2056f134e53f705a694ab85deeecabec5c
  extra-dep: true

# Required for explorer.
# We forked it because it has some unacceptable version bounds. We didn't
# add any features nor fix any bugs.
- location:
    git: https://github.com/yihuang/engine.io.git
    commit: 36ce634b5b39df27aec2581e64489ae7d4fc7198
  extra-dep: true
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai

# Library has never been released on Hackage yet
- location:
    git: https://github.com/yihuang/canonical-json.git
    commit: 2a6ae145120c189e0bdc3495fd22cdfb1d2cbb62
  extra-dep: true

# The latest release of clock on hackage is *way* too old (0.7.2)
# and can not be cross compiled.  As
# https://github.com/corsis/clock/commit/f7fe4fb5691d56c342e6fbf5a99c121ab24a6b41
# hasn't made it into any release yet.
- location:
    git: https://github.com/corsis/clock.git
    commit: ef60bd51a3587a173adf565c33bf2886df6e3842
  extra-dep: true

# Library has never been released on Hackage yet
- location:
    git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
    commit: 49f501a082d745f3b880677220a29cafaa181452
  extra-dep: true

# Because log-warper mainline depends on a lifted-async which depends upon a
# buggy async
- location:
    git: https://github.com/yihuang/log-warper.git
    commit: 30642de93d32ee292b8a2e2172072d4a7e4553e2
  extra-dep: true

# Exposes a custom discovery function so you can specify the prefix.
- location:
    git: https://github.com/yihuang/haskell-hedgehog.git
    commit: 3c1d3e07c4e51750192f2dcaa88d2ead93a6c449
  subdirs:
    - hedgehog
  extra-dep: true

# servant-quickcheck has a doc/doc.cabal file that is poorly specified and this
# breaks the mafia build tool.
- location:
    git: https://github.com/yihuang/servant-quickcheck.git
    commit: 703dfab66e91da2f3c4aa9de38e5a507bf1070be
  extra-dep: true

# Add custom stylish-haskell while waiting for PR upstream: https://github.com/jaspervdj/stylish-haskell/pull/214
- location:
    git: https://github.com/yihuang/stylish-haskell.git
    commit: 99a947da454cb4c6b5ec0639aa07ccfecc80883d
  extra-dep: true

# Custom Universum prelude, that brings back some of the
# formatting logic, as well as `pretty`.
- location:
    git: https://github.com/input-output-hk/universum.git
    commit: 7f1b2483f71cacdfd032fe447064d6e0a1df50fc
  extra-dep: true


# Need to adjust version bounds on serokell-util.
# serokell-util has an upper bound preventing 6.3 for some reason
- location:
    git: https://github.com/yihuang/serokell-util.git
    commit: 86564ef028fc99b4d065596d1ebebbd9f31e2db8
  extra-dep: true
- location:
    git: https://github.com/yihuang/micro-recursion-schemes.git
    commit: fed5905f6b19da953d24e32cef8e7aaa4634e855
  extra-dep: true

- location:
    git: https://github.com/tathougies/beam.git
    commit: 24a96f2f8d53558c33f1fe4031bd0687f9511e01
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-sqlite

- location:
    git: https://github.com/yihuang/haskell-chart.git
    commit: 048dec8cff045b6772d272f50634ca43f1fa6a6a
  extra-dep: true
  subdirs:
    - chart-diagrams
    - chart

- location:
    git: https://github.com/diagrams/diagrams-postscript.git
    commit: 87227d5f3c8e8c4a0242ccf82c8dd4383fc1af67
  extra-dep: true

# seal-contract
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true

- location:
    git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
  extra-dep: true

extra-deps:
# Serokell-specific utilities not on stackage
- fmt-0.6

# Following 10 are not on stackage.
- pvss-0.2.0
- systemd-1.1.2
- base58-bytestring-0.1.0
- pipes-interleave-1.1.3
- tabl-1.0.3
- loc-0.1.3.4
- json-sop-0.2.0.3
- lens-sop-0.2.0.2
- lzma-clib-5.2.2

# Servant stuff not found on stackage
- servant-multipart-0.11.3

# Graphics stuff not found on stackage.
- graphviz-2999.20.0.3

# Needed for coin selection in the wallet
- normaldistribution-1.1.0.3

# universum depends on tasty-hedgehog
# tasty-hedgehog < 0.2 depends on hedgehog < 0.6
# LTS-11.13 -- LTS-11.17 provide tasty-hedgehog-0.1.0.2
# thus to use our hedgehog-0.6+ from source,
# we need to explicilty bump tasty-hedgehog to 0.2.0.0.
- tasty-hedgehog-0.2.0.0
- lrucache-1.2.0.1
- o-clock-1.0.0.1
- ekg-0.4.0.15
- ekg-wai-0.1.0.3
- ekg-json-0.1.0.6
- ether-0.5.1.0
- nibblestring-0.0.3
- containers-0.5.11.0

#seal-contract
# - algebraic-graphs-0.3
# - trifecta-2
- FloatingHex-0.4
- compactable-0.1.2.3
- ed25519-donna-0.1.1
- hw-hspec-hedgehog-0.1.0.5
# - aeson-1.4.2.0
- criterion-1.5.3.0
# - hspec-2.6.1
# - lens-4.17
- megaparsec-6.5.0
- neat-interpolation-0.3.2.1
# - parser-combinators-0.4.0
- statistics-0.14.0.2
- stm-2.5.0.0
# - vector-space-0.15

# - ghc-boot-th-8.6.3
- cpphs-1.20.8
- happy-1.19.9

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

ghc-options:
  seal:                   -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-binary:            -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-binary-test:       -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-chain:             -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-chain-test:        -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-core:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-core-test:         -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-crypto:            -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-crypto-test:       -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-db:                -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-db-test:           -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-infra:             -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-networking:        -Werror -Wcompat -fwarn-redundant-constraints
  seal-node:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-x509:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-tools:             -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-tools-post-mortem: -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-util:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-util-test:         -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-rocksdb:           -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-mpt:               -Wall -Werror -Wcompat -fwarn-redundant-constraints
  seal-contract:          -Wall -Werror -Wcompat -fwarn-redundant-constraints
